# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ik.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ik.proto\x12\x02ik\"^\n\tIKRequest\x12\x1b\n\x06target\x18\x01 \x01(\x0b\x32\x0b.ik.Vector3\x12\x1d\n\x08rotation\x18\x02 \x01(\x0b\x32\x0b.ik.Vector3\x12\x15\n\rcurrentJoints\x18\x03 \x03(\x02\"\"\n\nIKResponse\x12\x14\n\x0cjointTargets\x18\x01 \x03(\x02\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x32\x9b\x01\n\x12KinematicsProvider\x12\x42\n\x1f\x43\x61lculateInverseKinematicsRight\x12\r.ik.IKRequest\x1a\x0e.ik.IKResponse\"\x00\x12\x41\n\x1e\x43\x61lculateInverseKinematicsLeft\x12\r.ik.IKRequest\x1a\x0e.ik.IKResponse\"\x00\x62\x06proto3')



_IKREQUEST = DESCRIPTOR.message_types_by_name['IKRequest']
_IKRESPONSE = DESCRIPTOR.message_types_by_name['IKResponse']
_VECTOR3 = DESCRIPTOR.message_types_by_name['Vector3']
IKRequest = _reflection.GeneratedProtocolMessageType('IKRequest', (_message.Message,), {
  'DESCRIPTOR' : _IKREQUEST,
  '__module__' : 'ik_pb2'
  # @@protoc_insertion_point(class_scope:ik.IKRequest)
  })
_sym_db.RegisterMessage(IKRequest)

IKResponse = _reflection.GeneratedProtocolMessageType('IKResponse', (_message.Message,), {
  'DESCRIPTOR' : _IKRESPONSE,
  '__module__' : 'ik_pb2'
  # @@protoc_insertion_point(class_scope:ik.IKResponse)
  })
_sym_db.RegisterMessage(IKResponse)

Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3,
  '__module__' : 'ik_pb2'
  # @@protoc_insertion_point(class_scope:ik.Vector3)
  })
_sym_db.RegisterMessage(Vector3)

_KINEMATICSPROVIDER = DESCRIPTOR.services_by_name['KinematicsProvider']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IKREQUEST._serialized_start=16
  _IKREQUEST._serialized_end=110
  _IKRESPONSE._serialized_start=112
  _IKRESPONSE._serialized_end=146
  _VECTOR3._serialized_start=148
  _VECTOR3._serialized_end=190
  _KINEMATICSPROVIDER._serialized_start=193
  _KINEMATICSPROVIDER._serialized_end=348
# @@protoc_insertion_point(module_scope)
