# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ik_pb2 as ik__pb2


class KinematicsProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateInverseKinematicsRight = channel.unary_unary(
                '/ik.KinematicsProvider/CalculateInverseKinematicsRight',
                request_serializer=ik__pb2.IKRequest.SerializeToString,
                response_deserializer=ik__pb2.IKResponse.FromString,
                )
        self.CalculateInverseKinematicsLeft = channel.unary_unary(
                '/ik.KinematicsProvider/CalculateInverseKinematicsLeft',
                request_serializer=ik__pb2.IKRequest.SerializeToString,
                response_deserializer=ik__pb2.IKResponse.FromString,
                )


class KinematicsProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateInverseKinematicsRight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateInverseKinematicsLeft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KinematicsProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateInverseKinematicsRight': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateInverseKinematicsRight,
                    request_deserializer=ik__pb2.IKRequest.FromString,
                    response_serializer=ik__pb2.IKResponse.SerializeToString,
            ),
            'CalculateInverseKinematicsLeft': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateInverseKinematicsLeft,
                    request_deserializer=ik__pb2.IKRequest.FromString,
                    response_serializer=ik__pb2.IKResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ik.KinematicsProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KinematicsProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateInverseKinematicsRight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ik.KinematicsProvider/CalculateInverseKinematicsRight',
            ik__pb2.IKRequest.SerializeToString,
            ik__pb2.IKResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateInverseKinematicsLeft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ik.KinematicsProvider/CalculateInverseKinematicsLeft',
            ik__pb2.IKRequest.SerializeToString,
            ik__pb2.IKResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
